In [1]:
import torch

In [5]:
X = torch.arange(20, dtype=torch.float32).reshape(5,4)
Y = X.clone()  # 克隆一个新矩阵
Y += Y
X, X.shape, Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 torch.Size([5, 4]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

矩阵乘法

In [24]:
a = torch.arange(6).reshape((2,3))
b = torch.ones((2,3))
b *=2 
c = a * b  # 矩阵元素相乘

In [25]:
a,b,c

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 tensor([[2., 2., 2.],
         [2., 2., 2.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [26]:
a.sum(), c.sum(),

(tensor(15), tensor(30.))

In [28]:
 a.sum(axis=0), c.sum(axis=1), a.cumsum(axis=0), a.cumsum(axis=1)

(tensor([3, 5, 7]),
 tensor([ 6., 24.]),
 tensor([[0, 1, 2],
         [3, 5, 7]]),
 tensor([[ 0,  1,  3],
         [ 3,  7, 12]]))

In [19]:
 suma = a.sum(axis=1, keepdims=True)  # 保持维度，广播机制

In [22]:
suma, suma.shape, a/suma

(tensor([[ 3],
         [12]]),
 torch.Size([2, 1]),
 tensor([[0.0000, 0.3333, 0.6667],
         [0.2500, 0.3333, 0.4167]]))

In [41]:
# 点击
d = torch.dot(torch.tensor([1,2,3]), torch.tensor([1,1,1]))
d, a.shape, b.shape, b.T.shape

(tensor(6), torch.Size([2, 3]), torch.Size([2, 3]), torch.Size([3, 2]))

In [37]:
u = torch.norm(torch.tensor([3.0, 4.0]))
u

tensor(5.)

# 维度 求和

In [44]:
a = torch.ones((2,5,4))
a.shape

torch.Size([2, 5, 4])

In [47]:
a.sum(axis=1).shape, a.sum(axis=0).shape

(torch.Size([2, 4]), torch.Size([5, 4]))

In [50]:
a.sum(axis=1, keepdims=True).shape

torch.Size([2, 1, 4])

In [53]:
print(a.sum(axis=[0, 2], keepdims=True).shape, 
a.sum(axis=[0, 2], keepdims=True) )

torch.Size([1, 5, 1]) tensor([[[8.],
         [8.],
         [8.],
         [8.],
         [8.]]])


# 自动求导

In [1]:
import torch

In [4]:
x = torch.arange(4.0, requires_grad=True)
# x.requires_grad(True)
# x.grad  # 默认值 None
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [5]:
y.backward()  # 求导
x.grad

tensor([ 0.,  4.,  8., 12.])

In [6]:
x.grad == 4 * x

tensor([True, True, True, True])

In [8]:
# 默认情况下梯度会累积
x.grad.zero_()
y = x.sum()
# y = x * x
# y.sum().backward()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [9]:
# 将某些计算移动到计算图之外
x.grad.zero_()
y = x * x
u = y.detach()  # 常数
z = u * x
z.sum().backward()
x.grad

tensor([0., 1., 4., 9.])